apiVersion: apps/v1
kind: Deployment
metadata:
  name: messageservice-deployment
  labels:
    app: messageservice
spec:
  replicas: 32
  selector:
    matchLabels:
      app: messageservice
  template:
    metadata:
      labels:
        app: messageservice
    spec:
      containers:
      - name: messageservice
        image: testappreg001.azurecr.io/messagingservice:v1
        imagePullPolicy: Always