apiVersion: apps/v1
kind: Deployment
metadata:
  name: rulesetservice-deployment
  labels:
    app: rulesetservice
spec:
  replicas: 32
  selector:
    matchLabels:
      app: rulesetservice
  template:
    metadata:
      labels:
        app: rulesetservice
    spec:
      containers:
      - name: rulesetservice
        image: testappreg001.azurecr.io/rulesetservice:v1
        imagePullPolicy: Always